# 更多细节请参考 demo: https://github.com/dongyuanxin/theme-bmw/blob/master/demo._config.yml
keywords: Hexo, theme-bmw

# 站点图标和APP图标
favicon: 
  icon: /images/favicon.ico
  touch_icon: /images/touch-icon.jpg

# RSS文件位置
rss: 

# 自定义样式文件位置
custom_style: 

# 自定义脚本：支持自定义多个脚本文件
# src: 文件位置
# load: <script>加载方式(async/defer/默认)
custom_script: 
  # - 
  #   src: 
  #   load: 
  # - 
  #   src: 
  #   load:

# 是否渲染 文章目录
toc: true

# 是否支持 数学公式
mathjax: true

# 是否开启 音乐组件
player: true

# 是否开启 分享功能: https://github.com/overtrue/share.js
social_share:
  enable: true
  sites: qzone, qq, weibo, wechat, douban, google, facebook, twitter
  disabled: 

# 是否开启 打赏功能
reward: 
  enable: true
  meta: 知识 & 情怀 | 二者兼得 # 提示文字
  button_meta: 投食 # 按钮文字
  qrcodes: 
    # 支持多个支付方式
    # src: 二维码位置
    # meta: 二维码提示信息
    -
      src: /images/wechat.jpg 
      meta: "微信扫一扫, 向我投食"
    -
      src: /images/20190430151936.jpg
      meta: "微信扫一扫, 做个好朋友"
    -
      src: /images/alipay.jpg
      meta: "支付宝扫一扫, 向我投食"

# 是否开启版权声明
# author: 您的名字
# license: 声明信息(支持html)
copyright: 
  enable: true
  author: 辰颐物语总代招商(微信yanxuanhui8) 
  license: '本媒体部分图片文章来源于网络,版权归原作者所有,如有侵权,请与我联系删除!'

# 页脚信息 
# start: 建站时间. 格式：YYYY-MM-DD
# more: 自定义页脚信息(支持HTML)
footer: 
  start: '2018-02-10'
  more: 

# 如何开启 评论&统计 插件：https://godbmw.com/passages/2018-11-15-theme-bmw-docs-zh/
# 请申请自己的 appid 和 appkey，并且替换下面的 appid 和 appkey
leancloud:
  appid: 6tM75t8zehLQYRhIctYBpEY1-gzGzoHsz # 填写您的appid
  appkey: dezgaFuw3Xb9xLjpEVt833iT # 填写您的appkey
  comment: false # 是否开启评论系统
  timer: true # 是否开启文章统计

# 导航栏头部名称
nav_name: 辰颐物语 

# 导航栏选项
# blank: 是否在新页面打开，默认 false
# children：开启二级导航栏
nav: 
  - 
    name: 主页
    path: /
  -
    name: 归档
    path: /archives/
  -
    name: 分类
    path: /categories/
  -
    name: 标签
    path: /tags/
  -
    name: 友链
    path: /friends/
  - 
    name: 关于
    path: /about/
  - 
    name: 抓到我
    children:
      -
        name: Github
        path: "https://github.com/live17909/"
        blank: true
     # -
     #   name: "知乎"
     #   path: "https://www.zhihu.com/people/godbmw/activities"
     #   blank: true

# 友链详细信息：支持多个友链
friends:
  -
    nickname: 辰颐物语总代招商(微信yanxuanhui8) # 昵称
    avatar: https://cdn.jsdelivr.net/gh/live17909/vxyanxuanhui8@1.1.1/img/kk.png # 头像链接
    site: http://blog.ifruit8.cn/ # 站点地址
    meta: 【辰颐物语】是以绿色健康为理念，新鲜美味为宗旨，从枝头到舌尖只有一条信息的距离，保证所有水果均为摘下就发货，不催熟，不泡药，没有冻库货，不管是老人小孩还是孕妇都吃的安心！ # 站点描述